DROP TABLE collaborateur IF EXISTS;

CREATE TABLE collaborateur (
     id int8 NOT NULL PRIMARY KEY,
     uid VARCHAR(255),
     civilite VARCHAR(255),
     nom VARCHAR(255),
     prenom VARCHAR(255),
     fonction VARCHAR(255),
     telephone VARCHAR(255),
     mail VARCHAR(255),
     etage VARCHAR(255),
     uo_affectation VARCHAR(255),
     code_immeuble_emplacement_collaborateur VARCHAR(255),
     region VARCHAR(255),
     code_region VARCHAR(255),
     niveau_territoire VARCHAR(255),
     code_territoire VARCHAR(255),
     niveau_entite VARCHAR(255),
     code_entite VARCHAR(255),
     niveau_agence VARCHAR(255),
     code_agence VARCHAR(255),
     localisation_collaborateur VARCHAR(255),
     pj VARCHAR(255),
     a_migrer VARCHAR(255),
     create_date_time TIMESTAMP,
     update_date_time TIMESTAMP
  );

create table output_file (
     id int8 NOT NULL PRIMARY KEY,
     action VARCHAR(255),
     administration VARCHAR(255),
     agent VARCHAR(255),
     alertes_seuil_supervisees VARCHAR(255),
     annuaires_supervises VARCHAR(255),
     campagnes VARCHAR(255),
     canaux_externes VARCHAR(255),
     categories_alertes VARCHAR(255),
     commentaires VARCHAR(255),
     competences VARCHAR(255),
     competences_supervisees VARCHAR(255),
     compteurs_supervises VARCHAR(255),
     configuration_afficheurs_muraux VARCHAR(255),
     domaine VARCHAR(255),
     domaines_supervises VARCHAR(255),
     email VARCHAR(255),
     email_commerciale VARCHAR(255),
     enregistrement VARCHAR(255),
     equipe VARCHAR(255),
     equipes_supervisees VARCHAR(255),
     flux_supervises VARCHAR(255),
     groupe_competence VARCHAR(255),
     groupes_reporting VARCHAR(255),
     groupes_supervises VARCHAR(255),
     historique VARCHAR(255),
     hypervision VARCHAR(255),
     identifiant VARCHAR(255),
     langue VARCHAR(255),
     missions_supervisees VARCHAR(255),
     mobile VARCHAR(255),
     modèles_alertes VARCHAR(255),

     panneaux_supervises VARCHAR(255),
     pauses_supervisees VARCHAR(255),
     plannings_supervises VARCHAR(255),
     position_commerciale VARCHAR(255),
     position_privee VARCHAR(255),
     prenom VARCHAR(255),
     profil VARCHAR(255),
     profils_supervises VARCHAR(255),
     scripting VARCHAR(255),
     services_supervises VARCHAR(255),
     site VARCHAR(255),
     sites_supervises VARCHAR(255),
     statistiques VARCHAR(255),
     strategies_routage_supervisees VARCHAR(255),
     suivi_actions VARCHAR(255),
     suivi_appels VARCHAR(255),
     supervision VARCHAR(255),
     tâches_supervisees VARCHAR(255),
     create_date_time TIMESTAMP,
     update_date_time TIMESTAMP
  );