CREATE TABLE collaborateur (
     id int8 NOT NULL PRIMARY KEY,
     uid VARCHAR(255),
     civilite VARCHAR(255),
     nom VARCHAR(255),
     prenom VARCHAR(255),
     fonction VARCHAR(255),
     telephone VARCHAR(255),
     mail VARCHAR(255),
     etage VARCHAR(255),
     uo_affectation VARCHAR(255),
     code_immeuble_emplacement_collaborateur VARCHAR(255),
     region VARCHAR(255),
     code_region VARCHAR(255),
     niveau_territoire VARCHAR(255),
     code_territoire VARCHAR(255),
     niveau_entite VARCHAR(255),
     code_entite VARCHAR(255),
     niveau_agence VARCHAR(255),
     code_agence VARCHAR(255),
     localisation_collaborateur VARCHAR(255),
     pj VARCHAR(255),
     a_migrer VARCHAR(255),
     create_date_time TIMESTAMP,
     update_date_time TIMESTAMP
  );

create table output_file (
     id int8 NOT NULL PRIMARY KEY,
     action VARCHAR(50),
     identifiant VARCHAR(6),
     nom VARCHAR(255),
     prenom VARCHAR(255),
     email VARCHAR(255),
     email_commerciale VARCHAR(50),
     langue VARCHAR(10),
     domaine VARCHAR(255),
     equipe VARCHAR(255),
     groupe_competence VARCHAR(50),
     groupes_reporting VARCHAR(50),
     profil VARCHAR(255),
     administration VARCHAR(50),
     supervision VARCHAR(50),
     agent VARCHAR(50),
     statistiques VARCHAR(50),
     enregistrement VARCHAR(50),
     campagnes VARCHAR(50),
     scripting VARCHAR(50),
     historique VARCHAR(50),
     suivi_actions VARCHAR(50),
     suivi_appels VARCHAR(50),
     configuration_afficheurs_muraux VARCHAR(50),
     hypervision VARCHAR(50),
     competences VARCHAR(255),
     site VARCHAR(50),
     position_privee VARCHAR(50),
     position_commerciale VARCHAR(50),
     mobile VARCHAR(50),
     domaines_supervises VARCHAR(50),
     equipes_supervisees VARCHAR(50),
     flux_supervises VARCHAR(50),
     competences_supervisees VARCHAR(50),
     groupes_supervises VARCHAR(50),
     sites_supervises VARCHAR(50),
     canaux_externes VARCHAR(50),
     pauses_supervisees VARCHAR(50),
     taches_supervisees VARCHAR(50),
     compteurs_supervises VARCHAR(50),
     services_supervises VARCHAR(50),
     alertes_seuil_supervisees VARCHAR(50),
     categories_alertes VARCHAR(50),
     modeles_alertes VARCHAR(50),
     panneaux_supervises VARCHAR(50),
     missions_supervisees VARCHAR(50),
     annuaires_supervises VARCHAR(50),
     strategies_routage_supervisees VARCHAR(50),
     profils_supervises VARCHAR(50),
     plannings_supervises VARCHAR(50),
     commentaires VARCHAR(50),
     create_date_time TIMESTAMP,
     update_date_time TIMESTAMP
  );
  
